name: Test GitHub Apps Action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run GitHub Apps Action
        uses: ./
        with:
          github_token: ${{ secrets.ORG_AUDIT_TOKEN }}
          org_name: yubi-migration

      - name: Upload GitHub Apps report
        uses: actions/upload-artifact@v4
        with:
          name: github-apps-report
          path: "*.csv"
